// Nueva base de datos con palabras renovadas
const database = {
    lugares: [
        { word: "Faro", hints: { easy: "Luz", medium: "Costa", hard: "Guía", very_hard: "Torre costera" } },
        { word: "Granja", hints: { easy: "Animales", medium: "Campo", hard: "Tractor", very_hard: "Explotación agraria" } },
        { word: "Iglú", hints: { easy: "Hielo", medium: "Esquimal", hard: "Domo", very_hard: "Refugio inuit" } },
        { word: "Pirámide", hints: { easy: "Egipto", medium: "Triángulo", hard: "Faraón", very_hard: "Tumba monumental" } },
        { word: "Acuario", hints: { easy: "Peces", medium: "Cristal", hard: "Tanque", very_hard: "Exhibición marina" } },
        { word: "Bolera", hints: { easy: "Bolos", medium: "Zapatos", hard: "Strike", very_hard: "Pista de madera" } },
        { word: "Fábrica", hints: { easy: "Humo", medium: "Máquinas", hard: "Producción", very_hard: "Manufactura" } },
        { word: "Laboratorio", hints: { easy: "Ciencia", medium: "Tubos", hard: "Bata", very_hard: "Experimentación" } },
        { word: "Mansión", hints: { easy: "Grande", medium: "Lujo", hard: "Mayordomo", very_hard: "Residencia palaciega" } },
        { word: "Mercado", hints: { easy: "Puestos", medium: "Comprar", hard: "Regatear", very_hard: "Bazar" } },
        { word: "Oficina", hints: { easy: "Trabajo", medium: "Ordenador", hard: "Jefe", very_hard: "Cubículo" } },
        { word: "Prisión", hints: { easy: "Celdas", medium: "Guardias", hard: "Rejas", very_hard: "Centro penitenciario" } },
        { word: "Tienda de campaña", hints: { easy: "Camping", medium: "Lona", hard: "Estacas", very_hard: "Refugio portátil" } },
        { word: "Tren", hints: { easy: "Vías", medium: "Estación", hard: "Vagón", very_hard: "Locomotora" } },
        { word: "Universidad", hints: { easy: "Estudios", medium: "Campus", hard: "Grado", very_hard: "Alma mater" } },
        { word: "Parque de Atracciones", hints: { easy: "Diversión", medium: "Montaña rusa", hard: "Ticket", very_hard: "Feria temática" } },
        { word: "Estación de Bomberos", hints: { easy: "Camión rojo", medium: "Sirena", hard: "Barra", very_hard: "Cuartel ignífugo" } },
        { word: "Comisaría", hints: { easy: "Policía", medium: "Denuncia", hard: "Calabozo", very_hard: "Jefatura" } },
        { word: "Gasolinera", hints: { easy: "Coche", medium: "Combustible", hard: "Manguera", very_hard: "Estación de servicio" } },
        { word: "Peluquería", hints: { easy: "Pelo", medium: "Tijeras", hard: "Espejo", very_hard: "Salón de belleza" } }
    ],
    comida: [
        { word: "Tortilla de patatas", hints: { easy: "Huevo", medium: "España", hard: "Sartén", very_hard: "Tubérculo frito" } },
        { word: "Croissant", hints: { easy: "Desayuno", medium: "Francia", hard: "Cuernos", very_hard: "Bollería hojaldrada" } },
        { word: "Ensaladilla Rusa", hints: { easy: "Patata", medium: "Mayonesa", hard: "Tapa", very_hard: "Mezcla fría" } },
        { word: "Gazpacho", hints: { easy: "Tomate", medium: "Frío", hard: "Sopa", very_hard: "Hortalizas trituradas" } },
        { word: "Lentejas", hints: { easy: "Legumbre", medium: "Cuchara", hard: "Hierro", very_hard: "Guiso pequeño" } },
        { word: "Macarrones", hints: { easy: "Pasta", medium: "Tubo", hard: "Italiano", very_hard: "Trigo duro" } },
        { word: "Churros", hints: { easy: "Chocolate", medium: "Desayuno", hard: "Frito", very_hard: "Masa estriada" } },
        { word: "Tarta de queso", hints: { easy: "Postre", medium: "Galleta", hard: "Horno", very_hard: "Cheesecake" } },
        { word: "Batido", hints: { easy: "Leche", medium: "Fruta", hard: "Pajita", very_hard: "Licuado lácteo" } },
        { word: "Nachos", hints: { easy: "Queso", medium: "Triángulo", hard: "Cine", very_hard: "Totopos" } },
        { word: "Burrito", hints: { easy: "Mexicano", medium: "Enrollado", hard: "Frijoles", very_hard: "Tortilla de harina" } },
        { word: "Curry", hints: { easy: "India", medium: "Picante", hard: "Arroz", very_hard: "Mezcla de especias" } },
        { word: "Ramen", hints: { easy: "Japón", medium: "Fideos", hard: "Caldo", very_hard: "Sopa asiática" } },
        { word: "Brownie", hints: { easy: "Chocolate", medium: "Nueces", hard: "Cuadrado", very_hard: "Bizcocho denso" } },
        { word: "Magdalena", hints: { easy: "Desayuno", medium: "Papel", hard: "Esponjoso", very_hard: "Bollo pequeño" } },
        { word: "Turrón", hints: { easy: "Navidad", medium: "Almendra", hard: "Tableta", very_hard: "Dulce duro/blando" } },
        { word: "Polvorón", hints: { easy: "Navidad", medium: "Harina", hard: "Se deshace", very_hard: "Mantecado" } },
        { word: "Roscón", hints: { easy: "Reyes", medium: "Fruta", hard: "Sorpresa", very_hard: "Bollo circular" } },
        { word: "Empanada", hints: { easy: "Masa", medium: "Relleno", hard: "Horno", very_hard: "Gallega" } },
        { word: "Fabada", hints: { easy: "Judías", medium: "Asturias", hard: "Compango", very_hard: "Guiso potente" } }
    ],
    animales: [
        { word: "Koala", hints: { easy: "Australia", medium: "Eucalipto", hard: "Abrazo", very_hard: "Marsupial arborícola" } },
        { word: "Canguro", hints: { easy: "Saltar", medium: "Bolsa", hard: "Boxeo", very_hard: "Macrópodo" } },
        { word: "Panda", hints: { easy: "Bambú", medium: "China", hard: "Blanco y negro", very_hard: "Oso asiático" } },
        { word: "Flamenco", hints: { easy: "Rosa", medium: "Una pata", hard: "Ave", very_hard: "Phoenicopterus" } },
        { word: "Camello", hints: { easy: "Desierto", medium: "Jorobas", hard: "Agua", very_hard: "Dromedario (primo)" } },
        { word: "Llama", hints: { easy: "Andes", medium: "Escupir", hard: "Lana", very_hard: "Camélido sudamericano" } },
        { word: "Perezoso", hints: { easy: "Lento", medium: "Árbol", hard: "Garras", very_hard: "Folívoro" } },
        { word: "Ornitorrinco", hints: { easy: "Pico", medium: "Huevo", hard: "Venenoso", very_hard: "Monotremata" } },
        { word: "Medusa", hints: { easy: "Mar", medium: "Picadura", hard: "Transparente", very_hard: "Cnidario" } },
        { word: "Estrella de mar", hints: { easy: "Cinco", medium: "Mar", hard: "Roca", very_hard: "Equinodermo" } },
        { word: "Caballito de mar", hints: { easy: "Mar", medium: "Pequeño", hard: "Papá paritorio", very_hard: "Hippocampus" } },
        { word: "Nutria", hints: { easy: "Río", medium: "Nadar", hard: "Manos", very_hard: "Mustélido acuático" } },
        { word: "Mapache", hints: { easy: "Antifaz", medium: "Basura", hard: "Rayas", very_hard: "Procyon" } },
        { word: "Erizo", hints: { easy: "Púas", medium: "Pequeño", hard: "Bola", very_hard: "Erinaceinae" } },
        { word: "Topo", hints: { easy: "Tierra", medium: "Ciego", hard: "Túnel", very_hard: "Talpidae" } },
        { word: "Búho", hints: { easy: "Noche", medium: "Ojos grandes", hard: "Girar cabeza", very_hard: "Ave estrigiforme" } },
        { word: "Colibrí", hints: { easy: "Pájaro", medium: "Rápido", hard: "Néctar", very_hard: "Trochilidae" } },
        { word: "Loro", hints: { easy: "Hablar", medium: "Colores", hard: "Pirata", very_hard: "Psittacidae" } },
        { word: "Avestruz", hints: { easy: "Correr", medium: "Grande", hard: "Huevo", very_hard: "Ave no voladora" } },
        { word: "Gorila", hints: { easy: "Selva", medium: "Fuerte", hard: "Pecho", very_hard: "Primate grande" } }
    ],
    profesiones: [
        { word: "Arqueólogo", hints: { easy: "Huesos", medium: "Excavar", hard: "Historia", very_hard: "Indiana Jones" } },
        { word: "Espía", hints: { easy: "Secreto", medium: "Misión", hard: "Disfraz", very_hard: "Agente encubierto" } },
        { word: "Mimo", hints: { easy: "Silencio", medium: "Cara blanca", hard: "Caja invisible", very_hard: "Teatro gestual" } },
        { word: "Escritor", hints: { easy: "Libros", medium: "Historias", hard: "Pluma", very_hard: "Autor" } },
        { word: "Bailarín", hints: { easy: "Música", medium: "Movimiento", hard: "Escenario", very_hard: "Coreografía" } },
        { word: "Granjero", hints: { easy: "Campo", medium: "Animales", hard: "Tractor", very_hard: "Agricultor" } },
        { word: "Pescador", hints: { easy: "Mar", medium: "Red", hard: "Barco", very_hard: "Captura" } },
        { word: "Minero", hints: { easy: "Cueva", medium: "Casco", hard: "Pico", very_hard: "Extracción" } },
        { word: "Taxista", hints: { easy: "Coche", medium: "Ciudad", hard: "Pasajero", very_hard: "Tarifa" } },
        { word: "Conductor de autobús", hints: { easy: "Vehículo grande", medium: "Paradas", hard: "Pasajeros", very_hard: "Transporte público" } },
        { word: "Arquitecto", hints: { easy: "Casas", medium: "Planos", hard: "Diseño", very_hard: "Edificación" } },
        { word: "Diseñador", hints: { easy: "Moda", medium: "Ropa", hard: "Estilo", very_hard: "Creativo" } },
        { word: "Modelo", hints: { easy: "Fotos", medium: "Pasarela", hard: "Ropa", very_hard: "Posar" } },
        { word: "Youtuber", hints: { easy: "Vídeos", medium: "Cámara", hard: "Internet", very_hard: "Creador de contenido" } },
        { word: "Streamer", hints: { easy: "Directo", medium: "Twitch", hard: "Juegos", very_hard: "Emisión en vivo" } },
        { word: "Gamer", hints: { easy: "Videojuegos", medium: "Mando", hard: "Consola", very_hard: "Jugador electrónico" } },
        { word: "Hacker", hints: { easy: "Ordenador", medium: "Código", hard: "Seguridad", very_hard: "Pirata informático" } },
        { word: "Músico", hints: { easy: "Instrumento", medium: "Notas", hard: "Banda", very_hard: "Intérprete" } },
        { word: "Bibliotecario", hints: { easy: "Libros", medium: "Silencio", hard: "Préstamo", very_hard: "Archivo" } },
        { word: "Soldador", hints: { easy: "Metal", medium: "Máscara", hard: "Chispa", very_hard: "Fusión" } }
    ],
    deportes: [
        { word: "Taekwondo", hints: { easy: "Patada", medium: "Cinturón", hard: "Corea", very_hard: "Arte marcial" } },
        { word: "Sumo", hints: { easy: "Gordo", medium: "Japón", hard: "Empujar", very_hard: "Círculo" } },
        { word: "Lucha Libre", hints: { easy: "Máscara", medium: "Ring", hard: "Teatro", very_hard: "WWE" } },
        { word: "Skate", hints: { easy: "Tabla", medium: "Ruedas", hard: "Trucos", very_hard: "Monopatín" } },
        { word: "Snowboard", hints: { easy: "Nieve", medium: "Tabla", hard: "Descenso", very_hard: "Deporte de invierno" } },
        { word: "Curling", hints: { easy: "Hielo", medium: "Escoba", hard: "Piedra", very_hard: "Diana horizontal" } },
        { word: "Patinaje sobre hielo", hints: { easy: "Frío", medium: "Cuchillas", hard: "Pista", very_hard: "Deslizamiento" } },
        { word: "Gimnasia Rítmica", hints: { easy: "Cinta", medium: "Música", hard: "Baile", very_hard: "Aro y pelota" } },
        { word: "Hípica", hints: { easy: "Caballo", medium: "Saltos", hard: "Jinete", very_hard: "Equitación" } },
        { word: "Dardos", hints: { easy: "Diana", medium: "Bar", hard: "Puntería", very_hard: "Punta" } },
        { word: "Petanca", hints: { easy: "Bolas", medium: "Parque", hard: "Metal", very_hard: "Juego de mayores" } },
        { word: "Críquet", hints: { easy: "Bate plano", medium: "Inglaterra", hard: "Hierba", very_hard: "Wickets" } },
        { word: "Lacrosse", hints: { easy: "Red", medium: "Palo", hard: "Bola", very_hard: "Campo" } },
        { word: "Parkour", hints: { easy: "Saltos", medium: "Calle", hard: "Edificios", very_hard: "Desplazamiento" } },
        { word: "Paracaidismo", hints: { easy: "Avión", medium: "Caída", hard: "Mochila", very_hard: "Cielo" } },
        { word: "Puenting", hints: { easy: "Cuerda", medium: "Salto", hard: "Puente", very_hard: "Adrenalina" } },
        { word: "Rafting", hints: { easy: "Río", medium: "Balsa", hard: "Remos", very_hard: "Aguas bravas" } },
        { word: "Senderismo", hints: { easy: "Caminar", medium: "Montaña", hard: "Mochila", very_hard: "Ruta" } },
        { word: "Yoga", hints: { easy: "Posturas", medium: "Relajación", hard: "Estirar", very_hard: "Esterilla" } },
        { word: "Crossfit", hints: { easy: "Gimnasio", medium: "Intenso", hard: "Pesas", very_hard: "Entrenamiento funcional" } }
    ],
    instrumentos: [
        { word: "Contrabajo", hints: { easy: "Grande", medium: "Cuerdas", hard: "Jazz", very_hard: "De pie" } },
        { word: "Fagot", hints: { easy: "Viento", medium: "Largo", hard: "Madera", very_hard: "Doble caña grave" } },
        { word: "Trompa", hints: { easy: "Circular", medium: "Metal", hard: "Mano dentro", very_hard: "Corno francés" } },
        { word: "Marimba", hints: { easy: "Madera", medium: "Golpear", hard: "Teclas", very_hard: "Xilófono grande" } },
        { word: "Vibráfono", hints: { easy: "Metal", medium: "Motor", hard: "Jazz", very_hard: "Percusión melódica" } },
        { word: "Timbales", hints: { easy: "Tambores", medium: "Orquesta", hard: "Afinables", very_hard: "Percusión clásica" } },
        { word: "Mandolina", hints: { easy: "Pequeña", medium: "Cuerdas dobles", hard: "Redonda", very_hard: "Italia" } },
        { word: "Laúd", hints: { easy: "Antiguo", medium: "Cuerdas", hard: "Pera", very_hard: "Renacimiento" } },
        { word: "Clavecín", hints: { easy: "Piano antiguo", medium: "Cuerdas", hard: "Pinzada", very_hard: "Barroco" } },
        { word: "Órgano", hints: { easy: "Iglesia", medium: "Tubos", hard: "Teclado", very_hard: "Aire" } },
        { word: "Sintetizador", hints: { easy: "Eléctrico", medium: "Teclas", hard: "Sonidos", very_hard: "Modulación" } },
        { word: "Theremin", hints: { easy: "Sin tocar", medium: "Antenas", hard: "Ciencia ficción", very_hard: "Ondas electromagnéticas" } },
        { word: "Caja de música", hints: { easy: "Cuerda", medium: "Melodía", hard: "Bailarina", very_hard: "Cilindro de púas" } },
        { word: "Silbato", hints: { easy: "Soplar", medium: "Árbitro", hard: "Agudo", very_hard: "Señal" } },
        { word: "Didgeridoo", hints: { easy: "Tubo", medium: "Australia", hard: "Soplar", very_hard: "Aborigen" } },
        { word: "Balalaika", hints: { easy: "Rusia", medium: "Triángulo", hard: "Cuerdas", very_hard: "Folk" } },
        { word: "Cítara", hints: { easy: "Mesa", medium: "Cuerdas", hard: "Austria", very_hard: "El tercer hombre" } },
        { word: "Lira", hints: { easy: "Antigua", medium: "Grecia", hard: "Pequeña", very_hard: "Apolo" } },
        { word: "Bongos", hints: { easy: "Dos", medium: "Tambores", hard: "Manos", very_hard: "Caribe" } },
        { word: "Congas", hints: { easy: "Alto", medium: "Tambor", hard: "Suelo", very_hard: "Salsa" } }
    ],
    ropa: [
        { word: "Albornoz", hints: { easy: "Baño", medium: "Toalla", hard: "Casa", very_hard: "Secarse" } },
        { word: "Bikini", hints: { easy: "Playa", medium: "Dos piezas", hard: "Verano", very_hard: "Baño mujer" } },
        { word: "Esmoquin", hints: { easy: "Fiesta", medium: "Elegante", hard: "Pajarita", very_hard: "Gala hombre" } },
        { word: "Frac", hints: { easy: "Pingüino", medium: "Cola", hard: "Muy elegante", very_hard: "Director de orquesta" } },
        { word: "Kimono", hints: { easy: "Japón", medium: "Bata", hard: "Cinturón", very_hard: "Tradicional" } },
        { word: "Poncho", hints: { easy: "Manta", medium: "Lluvia", hard: "Sin mangas", very_hard: "América Latina" } },
        { word: "Sari", hints: { easy: "India", medium: "Tela", hard: "Vestido", very_hard: "Envolver" } },
        { word: "Túnica", hints: { easy: "Larga", medium: "Antiguo", hard: "Roma", very_hard: "Holgado" } },
        { word: "Capa", hints: { easy: "Superhéroe", medium: "Espalda", hard: "Drácula", very_hard: "Sin mangas" } },
        { word: "Uniforme", hints: { easy: "Trabajo", medium: "Iguales", hard: "Colegio", very_hard: "Reglamentario" } },
        { word: "Disfraz", hints: { easy: "Carnaval", medium: "Máscara", hard: "Fiesta", very_hard: "Personaje" } },
        { word: "Camisón", hints: { easy: "Dormir", medium: "Vestido", hard: "Noche", very_hard: "Pijama largo" } },
        { word: "Chándal", hints: { easy: "Deporte", medium: "Cómodo", hard: "Dos piezas", very_hard: "Gimnasia" } },
        { word: "Jersey", hints: { easy: "Lana", medium: "Invierno", hard: "Calor", very_hard: "Manga larga" } },
        { word: "Rebeca", hints: { easy: "Chaqueta", medium: "Botones", hard: "Punto", very_hard: "Cárdigan" } },
        { word: "Blusa", hints: { easy: "Camisa", medium: "Mujer", hard: "Botones", very_hard: "Elegante" } },
        { word: "Top", hints: { easy: "Corto", medium: "Verano", hard: "Ombligo", very_hard: "Sin mangas" } },
        { word: "Peto", hints: { easy: "Tirantes", medium: "Vaquero", hard: "Bolsillo", very_hard: "Granjero" } },
        { word: "Mono", hints: { easy: "Una pieza", medium: "Pantalón", hard: "Entero", very_hard: "Mecánico" } },
        { word: "Leggins", hints: { easy: "Ajustado", medium: "Elástico", hard: "Deporte", very_hard: "Mallas" } }
    ]
};